# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5837562f4ef49e393d3d118a17a75eee710a817f6a50b5fa915c225ac3d9578bf29cb625f0a64fb5500c0970e3cd3a2b34ccab38662797bddddbdcbe9046673e

test:
  secret_key_base: 96145c83af8c25ba1b1fe86236ee235aa3eac2330cbc090f993f1e6fa77b474a28b6e2840c36236ef06a6614ae51f5b5e5d50b0297264d2ce1934f3bcc1855a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
